openai_api_key: "sk-xxxxxxxxxxxxxxxxxxxx"
telegram_bot_token: "xxxxx"
telegram_chat_id: "xxxxx"
sec:
  queries:
    - PIPE Subscription Agreement
  days_back: 1
interval_minutes: 60
prompt: |
  Analyze the following SEC filing for any private investment opportunities that are still relevant as of {{current_date}}.

  Here's exactly what we're looking for:
  - Private investment opportunities only (PIPEs, pre-IPO rounds, convertible notes, bridge rounds)
  - They must still be open, pending, or at least possibly active as of today
  - Skip any public offerings or opportunities that are fully closed

  Please return only **one block per company**, in **under 120 words total**, and inside that block:
  - Summarize each opportunity as a bullet point (1–3 short ones is fine)
  - Make it readable and quick to scan, short phrases - no full sentences

  If there are **no such private investment opportunities**, respond only with:

  X

  If there **is** something relevant, respond in this exact format (and only this format):

  Company: [Name of the company]

  Opportunity:
  - [Short summary of opportunity 1]
  - [Short summary of opportunity 2]
  - ...

  Who to contact: [e.g. "Company directly", "Placement agent mentioned", "No contact listed"]
